#!/bin/bash

# Quick commands for AkBarbershop development

echo "🏆 AkBarbershop Hair Cut Serves - Command Helper"
echo "================================================"
echo ""
echo "Available commands:"
echo ""
echo "1. 🚀 Start development server"
echo "   npm run dev"
echo ""
echo "2. 🏗️  Build for production"
echo "   npm run build"
echo ""
echo "3. ▶️  Start production server"
echo "   npm start"
echo ""
echo "4. 🔍 Type check"
echo "   npm run typecheck"
echo ""
echo "5. 📦 Install dependencies"
echo "   npm install"
echo ""
echo "================================================"
echo ""
echo "Quick Start: Run 'npm run dev' to start!"
echo ""
